-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity aes_inv_cipher_Multiply is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (7 downto 0);
    y : IN STD_LOGIC_VECTOR (3 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of aes_inv_cipher_Multiply is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1B : STD_LOGIC_VECTOR (7 downto 0) := "00011011";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal trunc_ln89_fu_42_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln91_fu_46_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_74_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln86_fu_82_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_ln86_fu_68_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_60_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_fu_90_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln92_fu_96_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_124_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln86_1_fu_118_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln86_1_fu_132_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_110_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln86_1_fu_140_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln93_fu_146_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln86_2_fu_160_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln86_2_fu_174_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln92_fu_104_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln91_fu_54_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln86_2_fu_182_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln93_fu_154_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln94_2_fu_194_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln94_1_fu_188_p2 : STD_LOGIC_VECTOR (7 downto 0);


begin



    and_ln91_fu_54_p2 <= (x and select_ln91_fu_46_p3);
    and_ln92_fu_104_p2 <= (xor_ln86_fu_90_p2 and select_ln92_fu_96_p3);
    and_ln93_fu_154_p2 <= (xor_ln86_1_fu_140_p2 and select_ln93_fu_146_p3);
    ap_ready <= ap_const_logic_1;
    ap_return <= (xor_ln94_2_fu_194_p2 xor xor_ln94_1_fu_188_p2);
    select_ln86_1_fu_132_p3 <= 
        ap_const_lv8_1B when (tmp_3_fu_124_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln86_2_fu_174_p3 <= 
        ap_const_lv8_1B when (tmp_4_fu_166_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln86_fu_82_p3 <= 
        ap_const_lv8_1B when (tmp_1_fu_74_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln91_fu_46_p3 <= 
        ap_const_lv8_FF when (trunc_ln89_fu_42_p1(0) = '1') else 
        ap_const_lv8_0;
    select_ln92_fu_96_p3 <= 
        ap_const_lv8_FF when (tmp_fu_60_p3(0) = '1') else 
        ap_const_lv8_0;
    select_ln93_fu_146_p3 <= 
        ap_const_lv8_FF when (tmp_2_fu_110_p3(0) = '1') else 
        ap_const_lv8_0;
    shl_ln86_1_fu_118_p2 <= std_logic_vector(shift_left(unsigned(xor_ln86_fu_90_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln86_2_fu_160_p2 <= std_logic_vector(shift_left(unsigned(xor_ln86_1_fu_140_p2),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    shl_ln86_fu_68_p2 <= std_logic_vector(shift_left(unsigned(x),to_integer(unsigned('0' & ap_const_lv8_1(8-1 downto 0)))));
    tmp_1_fu_74_p3 <= x(7 downto 7);
    tmp_2_fu_110_p3 <= y(2 downto 2);
    tmp_3_fu_124_p3 <= x(6 downto 6);
    tmp_4_fu_166_p3 <= x(5 downto 5);
    tmp_fu_60_p3 <= y(1 downto 1);
    trunc_ln89_fu_42_p1 <= y(1 - 1 downto 0);
    xor_ln86_1_fu_140_p2 <= (shl_ln86_1_fu_118_p2 xor select_ln86_1_fu_132_p3);
    xor_ln86_2_fu_182_p2 <= (shl_ln86_2_fu_160_p2 xor select_ln86_2_fu_174_p3);
    xor_ln86_fu_90_p2 <= (shl_ln86_fu_68_p2 xor select_ln86_fu_82_p3);
    xor_ln94_1_fu_188_p2 <= (and_ln92_fu_104_p2 xor and_ln91_fu_54_p2);
    xor_ln94_2_fu_194_p2 <= (xor_ln86_2_fu_182_p2 xor and_ln93_fu_154_p2);
end behav;
